[package]
name = "vex"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Package manager and build tool for the Wave programming language"
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords = ["wave", "package-manager", "build-tool"]
categories = ["command-line-utilities", "development-tools::build-utils"]
publish = false

[workspace]
members = ["diagnostic", ".", "manifest", "lockfile", "resolver", "compiler", "toolchain", "wson", "state", "source", "process"]
resolver = "2"

[workspace.package]
version = "0.0.2-beta"
edition = "2021"
rust-version = "1.96.0"
license = "MPL-2.0"
repository = "https://github.com/wavefnd/Vex"

[workspace.dependencies]
diagnostic = { path = "diagnostic" }
process = { path = "process" }
source = { path = "source" }
manifest = { path = "manifest" }
lockfile = { path = "lockfile" }
resolver = { path = "resolver" }
compiler = { path = "compiler" }
toolchain = { path = "toolchain" }
wson_rs = "0.2.5"
wson = { path = "wson" }
state = { path = "state" }
serde_json = "1.0"

[dependencies]
diagnostic.workspace = true
serde_json.workspace = true
process.workspace = true
source.workspace = true
colorex = "0.1.1"
manifest.workspace = true
lockfile.workspace = true
resolver.workspace = true
compiler.workspace = true
toolchain.workspace = true

state.workspace = true
