[package]
name = "resolver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
diagnostic.workspace = true
process.workspace = true
source.workspace = true
manifest.workspace = true
lockfile.workspace = true
state.workspace = true
serde_json.workspace = true
sha2 = "0.11"
